# Generated by Django 6.0.4 on 2026-05-03 16:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='meters', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_production', 'In Production'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer')),
            ],
            options={
                'ordering': ['-order_date', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('design_notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='shop.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('other', 'Other')], default='pickup', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('final_observations', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='shop.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('current_stage', models.CharField(choices=[('order_received', 'Order Received'), ('design_confirmed', 'Design Confirmed'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], default='order_received', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('deadline', models.DateField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='shop.employee')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='shop.garment')),
            ],
            options={
                'ordering': ['deadline', 'ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('order_received', 'Order Received'), ('design_confirmed', 'Design Confirmed'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('quality_check', 'Quality Check'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_updates', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shop.workticket')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GarmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garment_materials', to='shop.garment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garment_materials', to='shop.material')),
            ],
            options={
                'ordering': ['garment_id', 'material__name'],
                'unique_together': {('garment', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='cm', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='shop.garment')),
            ],
            options={
                'ordering': ['garment_id', 'name'],
                'unique_together': {('garment', 'name')},
            },
        ),
    ]
