# Generated by Django 6.0.4 on 2026-05-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='primary_material',
            field=models.ForeignKey(blank=True, help_text='Main material chosen during order entry. Use detailed materials for quantities.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_garments', to='shop.material'),
        ),
    ]
