# Generated by Django 6.0.4 on 2026-05-08 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_date_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit for this garment.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit amount already received.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed total price for this order.', max_digits=10, null=True),
        ),
    ]
