# Generated by Django 6.0.4 on 2026-05-09 19:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def forwards_delivery_ready(apps, schema_editor):
    Delivery = apps.get_model("shop", "Delivery")
    for d in Delivery.objects.filter(status="ready"):
        d.status = (
            "ready_pickup" if d.method == "pickup" else "out_delivery"
        )
        d.save(update_fields=["status"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_garment_unit_price_order_deposit_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='specialty_stage',
            field=models.CharField(blank=True, help_text='Production stage code this person handles (e.g. sewing, cutting). Used when clicking “Next stage” on a ticket.', max_length=30),
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed base price for this garment type (before fabric surcharge).', max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('fabric', 'Fabric / textile'), ('trim', 'Trim / lining'), ('notions', 'Buttons, zippers, etc.'), ('other', 'Other')], default='fabric', help_text='Use Fabric for primary material on garments; buttons/notions belong here, not as “primary fabric”.', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='price_addon',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge when this material is chosen (per garment unit).', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='use_automatic_pricing',
            field=models.BooleanField(default=True, help_text='When on, order total is recalculated from garment types and fabric surcharges.'),
        ),
        migrations.RunPython(forwards_delivery_ready, noop_reverse),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_pickup', 'Ready for pickup'), ('out_delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_production', 'In Production'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='in_production', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='shop.delivery')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='shop.order')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='shop.workticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='cm', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_measurements', to='shop.customer')),
            ],
            options={
                'ordering': ['customer_id', 'name'],
                'unique_together': {('customer', 'name')},
            },
        ),
    ]
